### ISSUE TITLE
Spelling: "focussing" can be updated to "focusing"

### ISSUE THREAD

**Issue by johnsonstephan** [sigp/positions-vacant#14]
**Issue** 
Within "The Role" section, the 4th bullet point states `Experience with manual source code reviews of large code bases, focussing on security issues.`

**Proposal**
Update "focussing" to "focusing" -- by removing an 's'.

**Comment by zedt3ster** [comment]
I'm not a native English speaker so I had to look this up to be sure, but both spelling are correct.
